name: Android Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # Автозапуск по тэгам
  workflow_dispatch:  # Ручной запуск из UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Decode keystore from secrets
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > release.keystore

      - name: Build signed release APK
        env:
          KEYSTORE_FILE_PATH: release.keystore
          STORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_NAME: ${{ secrets.KEY_ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: app/build/outputs/apk/release/app-release.apk
          body: |
            # Release ${{ github.ref_name }}

            This is an automated release.

            ## Changelog
            (Add your changelog here)
